Api 87 etl para consumo ia de predi o de duplicatas
quarks-team/ProjetoIntegrador-SpcGrafeno-IA pull request #24
Opened 2024-10-27 02:03 UTC by guilherme0066

2024-10-27 03:30 UTC, FelipeASousa requested changes
Por gentileza, esconder o nome das colunas do dataframe original, e também o nome da tabela que aparece no arquivo xlsx

2024-10-27 16:26 UTC, guilherme0066 reviewed
alterei os nomes, tanto do arquivo de entrada quanto de saída. Tambem ocultei os nomes das colunas

2024-10-27 20:38 UTC, FelipeASousa approved these changes

2024-10-27 20:39 UTC, FelipeASousa approved these changes

2024-10-28 02:46 UTC, FelipeASousa approved these changes

2024-10-28 02:46 UTC, FelipeASousa commented on backendPython/app/__pycache__/config.cpython-312.pyc
OK

2024-10-28 02:52 UTC, merged